### ISSUE TITLE
Domain and procotol not working in route

### ISSUE THREAD

**Issue by cwhsu1984** [crysalead/router#3]
curl http://localhost/uuu

The domain and protocol params do seem to work, because curl returns "routing uuu" on
`echo $router->route($_SERVER['REQUEST_URI'], $_SERVER['REQUEST_METHOD'], 'www.domain.com')->dispatch(); 
`
or
`echo $router->route($_SERVER['REQUEST_URI'], $_SERVER['REQUEST_METHOD'], 'www.domain.com', 'https')->dispatch(); `

```
<?php

include __DIR__.'/vendor/autoload.php';

use Lead\Router\Router;

$router = new Router();

$router->bind('uuu', ['methods' => 'GET'], function () {
    return "routing uuu";
});

try {
    echo $router->route($_SERVER['REQUEST_URI'], $_SERVER['REQUEST_METHOD'], 'www.domain.com', 'https')->dispatch();                                                                                         
} catch (\Lead\Router\RouterException $e) {
    var_dump($e);
} catch (Exception $e) {
    var_dump($e);
}

```

**Comment by jails** [comment]
If a route is part of a domain you should define it through the [`group()` method](https://github.com/crysalead/router#sub-domain-andor-prefix-routing). 
```php
$router->group(['host' => 'www.domain.com'], function($router) {
    $router->bind('uuu', ['methods' => 'GET'], function () {
        return "routing uuu";
    });
});
```

**Comment by cwhsu1984** [comment]
man... these are basically from your document...

`$router->bind($pattern, ['methods' => 'GET'], $handler);           // route matching on only GET requests
`

```
use Lead\Router\Router;

$router = new Router();

$router->bind('foo/bar', function() {
    return "Hello World!";
});

$route = $router->route('foo/bar', 'GET', 'www.domain.com', 'https');

echo $route->dispatch(); // Can throw an exception if the route is not valid.
```

The only thing I do is just combing what you states in your document...

**Comment by jails** [comment]
and the doc is correct.

**Comment by cwhsu1984** [comment]
Seriously? Do you run these examples? Would you like me to record an video and show you the result?
I have spent more than 3 days on your project, and I found the most frustrated thing is that most your examples looks fine at the beginning. However, changing a little big of code would show that there are many problems!

For example, do explain this, why "curl localhost/foo/bar" returns "Hello World!"? **This is all just from your document.**

```
<?php

include __DIR__.'/vendor/autoload.php';

use Lead\Router\Router;

$router = new Router();

$router->bind('foo/bar', function() {
        return "Hello World!";
});

$route = $router->route('foo/bar', 'GET', 'www.domain.com', 'https');

echo $route->dispatch(); // Can throw an exception if the route is not valid. 
```

**Comment by jails** [comment]
No need video, if there's a bug open a PR with a failing test.
I share my work for free and I [did tests](https://github.com/crysalead/router/tree/master/spec/Suite) to prove it's working and how it's working.
So if you can't have a constructive an polite discussion, feel free to stop wasting my time and use another routing library.

**Comment by cwhsu1984** [comment]
Sorry for the impoliteness. I really think that the document could be improved and also clarified something for people who first use it, and there's my PR.
