### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by mkraha** [crysalead/router#5]
I get following error on Install with composer:
crysalead/router 3.0.6 requires php >=7 -> your PHP version (5.6.31) does not satisfy that requirement.

**Comment by jails** [comment]
Indeed this library requires a PHP version >= 7.
So unfortunately if you want to install this library you'll need to update your PHP version.

**Comment by mkraha** [comment]
Why didn't we add support from 5.6.x and up-to Current php version?

**Comment by jails** [comment]
Because it's time consuming to support old PHP versions.

**Comment by mkraha** [comment]
Right but its very useful one who use standard alone php application like me.
PS: Most of the hosting still not added php 7.

**Comment by jails** [comment]
No time for that sorry.
